---
nginx_config_directory: etc/avans-informatica-breda.nl/nginx
digitalocean_token: "{{ lookup('ENV', 'do_token') }}"

default_group:
  gid: 9000
  name: "rungroup"

default_user:
  uid: 9000
  name: "runuser"
  group: "{{ default_group.name }}"
  groups: [docker]

project_name: entrypoint
project_dir: srv/app

pip_install_packages:
  - name: setuptools
  - name: pyopenssl
    version: 16.2.0
  - name: certbot-dns-digitalocean
  - name: docker

nginx_host_letsencrypt_email: "{{ lookup('ENV', 'letsencryptEmail') }}"

nginx_image: "survivorbat/nginx-jinja2:1.17.9"
nginx_name: "nginx_entrypoint"
nginx_environment:
  hostname: "{{ inventory_hostname }}"
