---
- name: "Ensure groups exist"
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid|default(omit) }}"
    state: present
  with_items: "{{ common_groups }}"

- name: "Ensure users exist"
  user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password|default(omit) }}"
    groups: "{{ item.groups|default(omit) }}"
    shell: "/bin/bash"
    append: yes
    uid: "{{ item.uid|default(omit) }}"
  with_items: "{{ common_users }}"

- name: "Ensure users are able login with their public key"
  authorized_key:
    user: "{{ item.name }}"
    state: "present"
    key: "{{ item.ssh_public_key }}"
  with_items: "{{ common_users }}"

- name: "Ensure sudo groups have sudo permission"
  lineinfile:
    path: /etc/sudoers
    regexp: '^%{{ item }}'
    line: '%{{ item }} ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  with_items: "{{ sudo_groups }}"
